services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=pwr
      - POSTGRES_DB=ziwg_db

  eureka-server:
    build:
      context: .
      dockerfile: Discovery/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app-network

#  user-service:
#    build:
#      context: .
#      dockerfile: UserService/Dockerfile
#    depends_on:
#      - eureka-server
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
#    ports:
#      - "8082:8082"
#    networks:
#      - app-network
#    command: sh -c "sleep 15 && java -jar app.jar"


networks:
  app-network:
    driver: bridge
