services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: pwr
      POSTGRES_DB: ziwg_db
    networks:
      - app-network

  auth-service:
    build: ./AuthService
#    ports:
#      - "???:???"
    networks:
      - app-network

  config:
    build: ./Config
    ports:
      - "8888:8888"
    networks:
      - app-network

  discovery:
    build: ./Discovery
    ports:
      - "8761:8761"
    networks:
      - app-network

  gateway:
    build: ./Gateway
    ports:
      - "8080:8080"
    networks:
      - app-network

  reservation-service:
    build: ./ReservationService
    ports:
      - "8083:8083"
    networks:
      - app-network
    depends_on:
        - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ziwg_db

  user-service:
    build: ./UserService
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
        - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ziwg_db

  utils:
    build: ./Utils
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ziwg_db

  web:
    build: ./web
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
