services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=pwr
      - POSTGRES_DB=ziwg_db

#  web:
#    build: ./web
#    ports:
#      - "3000:80"
#    networks:
#      - app-network

#  user-service:
#    build: ./userService
#    ports:
#      - "8080:8080"
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
