spring:
  application:
    name: UserService
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
          true
  datasource:
    url: jdbc:postgresql://localhost:5432/ziwg_db  #kiedy robisz lokalnie
#    url: jdbc:postgresql://postgres:5432/ziwg_db # kiedy docker-compose
    username: pwr
    password: password
server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true